//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketsXchange.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public int Id { get; set; }
        public int TicketId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int Type { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> TableId { get; set; }
        public int Balance1 { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
